language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - export PATH=$PATH:~/casperjs/bin
before_script:
  - phantomjs --version
  - casperjs --version
